# -- basic settings -----------------------------------
# tmux prefix
unbind C-b
set -g prefix `

# navigation key bindings
set-window-option -g mode-keys vi

# terminal colors
# set -g default-terminal "screen-256color"
# - fix true color for ipython
set -ga terminal-overrides ',xterm-256color:RGB'

# new fix?
set -g default-terminal xterm-256color
set -sa terminal-overrides ',xterm-kitty:RGB'


# previous version notes
# - smart pane switching with awareness of vim splits.
#   - see: https://github.com/christoomey/vim-tmux-navigator
# - change status bar within ssh
# - nested tmux handler (allows for switching between inner and outer)


# -- plugins -----------------------------------------
# set up tmux plugin manager
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# rose pine theme
# set -g @plugin 'rose-pine/tmux'
# set -g @rose_pine_variant 'dawn' # Options are 'main', 'moon' or 'dawn'

# rose pine theming extras
# - see https://github.com/rose-pine/tmux?tab=readme-ov-file

# this must be the last line
run '~/.tmux/plugins/tpm/tpm'
