require "msho.options"
require "msho.keymaps"
require "msho.plugins"
require "msho.colorscheme"
require "msho.cmp"
require "msho.lsp"
require "msho.telescope"
require "msho.treesitter"
require "msho.autopairs"
require "msho.comment"
require "msho.gitsigns"
require "msho.nvim-tree"
require "msho.bufferline"
require "msho.lualine"
-- require "msho.toggleterm"
require "msho.project"
require "msho.impatient"
-- require "msho.indentline"
require "msho.alpha"
require "msho.whichkey"
require "msho.autocommands"
